/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface BookShortResponse {
  bookId?: number;
  bookName?: string;
  image?: string;
}
