/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface BookRequest {
  /**
   * @minLength 2
   * @maxLength 50
   */
  title: string;
  author: string;
  price?: number;
  stock?: number;
  image?: string;
}
