/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { BookShortResponse } from './bookShortResponse';

export interface OrderItemResponse {
  id?: number;
  book?: BookShortResponse;
  quantity?: number;
  price?: number;
}
