/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UserResponse } from './userResponse';
import type { OrderItemResponse } from './orderItemResponse';

export interface OrderResponse {
  user?: UserResponse;
  total?: number;
  status?: string;
  items?: OrderItemResponse[];
}
